### PR TITLE
New features

### PR DESCRIPTION
**Pull request by mrh929**
Add features:

1. Log will be saved in /data/local/tmp/wifiadb.log.
2. Magisk manager can control wifi adb status now (only when magisk-wifiadb is enabled at boot time).
3. ADB port can be changed in config file.

### CODE REVIEW

**Comment by aiamuzz** [comment]
@mrh929 ... I am still not clear on what you mean when you say ... **"Magisk manager can control wifi adb status now (only when magisk-wifiadb is enabled at boot time)."**

the only screen i see with a switch is the following screenshot ...

I am assuming if the module is enabled as seen in the following screenshot the wifiadb is configured to run on boot time. 

image

I am however unclear on how do i enable / disable wifiadb in real time without rebooting the phone.

**Comment by mrh929** [comment]
> @mrh929 ... I am still not clear on what you mean when you say ... **"Magisk manager can control wifi adb status now (only when magisk-wifiadb is enabled at boot time)."**
> 
> the only screen i see with a switch is the following screenshot ...
> 
> I am assuming if the module is enabled as seen in the following screenshot the wifiadb is configured to run on boot time.
> 
> image
> 
> I am however unclear on how do i enable / disable wifiadb in real time without rebooting the phone.

You need to understand a concept: the magisk module cannot monitor any behavior when it is not started, and there is no way to trigger it.

There are two situations:
- If you enable this module and reboot:
   The monitor service will always be on (which means it can detect button status). And you can configure WiFi ADB status without booting your phone. (You enable the module, ADB will be on. You disable the module, ADB will be off). This is useful when you want to disable WiFi ADB immediately but don't want to reboot.
- If you disable this module and reboot:
   Magisk will not start this service, and pressing the button does nothing. (I don't think I can write a script to trigger it, which doesn't abey magisk module's rule)

**Comment by aiamuzz** [comment]
> * If you enable this module and reboot:
>   The monitor service will always be on (which means it can detect button status). And you can configure WiFi ADB status without booting your phone. (You enable the module, ADB will be on. You disable the module, ADB will be off). This is useful when you want to disable WiFi ADB immediately but don't want to reboot.

ok ... let me see if i've got it right ...

1.  My screenshot currently has the module enabled as i've rebooted after enabling it - meaning the module is now configured to start on boot.

2. Now if i disable the module in the magisk manager **and don't restart the phone** - wifiadb will be OFF ?

3. If i go back to the magisk manager and enable it back **and don't restart the phone** - wifiadb will be ON ?

am i right ?

**Comment by mrh929** [comment]
> > * If you enable this module and reboot:
> >   The monitor service will always be on (which means it can detect button status). And you can configure WiFi ADB status without booting your phone. (You enable the module, ADB will be on. You disable the module, ADB will be off). This is useful when you want to disable WiFi ADB immediately but don't want to reboot.
> 
> ok ... let me see if i've got it right ...
> 
> 1.  My screenshot currently has the module enabled as i've rebooted after enabling it - meaning the module is now configured to start on boot.
> 
> 2. Now if i disable the module in the magisk manager **and don't restart the phone** - wifiadb will be OFF ?
> 
> 3. If i go back to the magisk manager and enable it back **and don't restart the phone** - wifiadb will be ON ?
> 
> am i right ?

Yes, exactly.
You can test this feature via your PC.

**Pull request merged**
